resource:
  mysql:
    host: 192.168.1.221
    port: 3306
  redis:
    host: 192.168.1.221
    port: 6379
  influxdb:
    host: 192.168.1.221
    port: 8086
spring:
  redis:
    database: 4

# zk
takin.pradar.zk.server: 192.168.1.178:2181


# mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
